### ISSUE TITLE
createMultiTag with a Duplicate name sometimes gives empty RuntimeError:

### ISSUE THREAD

**Issue by ajayramak** [G-Node/nixpy#114]
Dear Nix Developer team

When trying to create a multitag with a name that already exists in the parent block, sometimes I get

     RuntimeError: Duplicate name given - names have to be unique for a given entity type & parent. (createMultiTag)

and some other times:

     RuntimeError:

Please have a look and fix this.

Thanks
Ajay

**Comment by jgrewe** [comment]
Hi Ajay, after some digging I gave up on finding the cause for this problem. On the C++ side, the exceptions are correctly thrown and contain a correct error message. In python side they sometimes loose their messages. 
I created explicit transforms that map the nix::C++ exceptions to python errors. In case of empty messages, a standard error message is provided giving at least an idea what went wrong. (see pull request #119.

Thanks again for your bug report and the code!
