### ISSUE TITLE
tag.retrieve_data gives Segmentation Fault

### ISSUE THREAD

**Issue by ajayramak** [G-Node/nixpy#116]
Dear Nix Developer team

I tried to use tag.retrieve_data and got a Segmentation Fault . Here is the test code

    import nix
    import numpy as np
    from math import pi as PI
    import os
    from matplotlib import pyplot as plt

    fs = 1000.0
    t = np.arange(0, 10, 1 / fs)
    sig1 = np.random.rand(t.shape[0])
    sig2 = np.sin(2 * PI * 0.5 * t)

    fle = 'test.h5'

    if os.path.isfile(os.path.join(os.getcwd(), fle)):
      os.remove(fle)
      
    nixFile = nix.File.open(fle, nix.FileMode.Overwrite)
    blk = nixFile.create_block('blk1', 'testBlock')
    da1 = blk.create_data_array('sig1', 'test',  data=sig1)
    dim = da1.append_sampled_dimension(1 / fs)
    dim.unit = 's'
    da2 = blk.create_data_array('sig2', 'test', data=sig2)
    dim = da2.append_sampled_dimension(1 / fs)
    dim.unit = 's'

    tag1 = blk.create_tag('tag1', 'test', [2])
    tag1.extent = [0.5]

    tag1.references.append(da1)
    tag1.references.append(da2)

    snip1 = tag1.retrieve_data(0)
    t1 = np.linspace(0, tag1.extent[0], snip1.shape[0]) + tag1.position[0]

    plt.plot(t1, snip1)
    plt.show()

Please help me.

Thanks
Ajay

**Comment by ajayramak** [comment]
Dear Jan and Adrian

I added a unit to the tag and the segmentation fault does not occur any more. But the retrieved value is wrong when the reference has an offset. Here is the test code:

    import nix
    import numpy as np
    from math import pi as PI
    import os
    from matplotlib import pyplot as plt



    sig1 = np.arange(2, 10)

    fle = 'test.h5'

    if os.path.isfile(os.path.join(os.getcwd(), fle)):
      os.remove(fle)
      
    nixFile = nix.File.open(fle, nix.FileMode.Overwrite)
    blk = nixFile.create_block('blk1', 'testBlock')
    da1 = blk.create_data_array('sig1', 'test',  data=sig1)
    dim = da1.append_sampled_dimension(0.1)
    dim.unit = 's'
    dim.offset = 0.2


    tag1 = blk.create_tag('tag1', 'test', [0.4])
    tag1.extent = [0.2]
    tag1.units = ['s']
    tag1.references.append(da1)


    snip1 = tag1.retrieve_data(0)[:]
    print(snip1)

Expected output is [4 5] whereas the actual output is [6 7].

Please have a look.

Thanks and Cheers
Ajay

**Comment by jgrewe** [comment]
Hi Ajay,
this is related (actually the same) bug as in  #117 and is really the offset issue.
The fix is ready but I just stumbled over another issue I want to solve before submitting the patch.

Thanks again!

**Comment by jgrewe** [comment]
This bug is fixed in fixed in the cpp lib. Please update it and there should be no more seg faults.
