### ISSUE TITLE
multi_tag retrieves incorrect data

### ISSUE THREAD

**Issue by ajayramak** [G-Node/nixpy#117]
Dear Nix Developer Team

I was trying to use multi_tag.retrieve_data(). it retrieves wrong data.
Here is the test code.

    import nix
    import numpy as np
    from math import pi as PI
    import os
    from matplotlib import pyplot as plt

    sig1 = np.arange(2, 20)

    fle = 'test.h5'

    if os.path.isfile(os.path.join(os.getcwd(), fle)):
      os.remove(fle)
      
    nixFile = nix.File.open(fle, nix.FileMode.Overwrite)
    blk = nixFile.create_block('blk1', 'testBlock')
    da1 = blk.create_data_array('sig1', 'test',  data=sig1)
    dim = da1.append_sampled_dimension(0.1)
    dim.unit = 's'
    dim.offset = 0.2

    pos = blk.create_data_array('pos1', 'test', data=[0.4, 0.8, 1.2])
    pos.append_set_dimension()
    pos.append_set_dimension()

    ext = blk.create_data_array('ext1', 'test', data=[0.2, 0.2, 0.2])
    ext.append_set_dimension()
    ext.append_set_dimension()

    tag1 = blk.create_multi_tag('tag1', 'test', pos)
    tag1.extents = ext

    tag1.references.append(da1)

    snips = [tag1.retrieve_data(p, 0)[:] for p in range(3)]
    print(snips)

The expected output here is 
    [array([4, 5]), array([8, 9]), array([12, 13])]
whereas the output is
    [array([6, 7]), array([10, 11]), array([14, 15])]

It seems that the offset hasn't been taken into account.
Please have a look.

Cheers
Ajay

**Comment by jgrewe** [comment]
Hi Ajay,

the bug has been fixed in the cpp library. Please update the cpp lib and this bug should no longer occur.

Best,
Jan
