### ISSUE TITLE
Test fails with newest nixpy commit

### ISSUE THREAD

**Issue by ajayramak** [G-Node/nixpy#129]
Dear Nix developer team

I tried to build nixpy and a test failed. Here are some details:

nix version installed: commit 7fd231bc753ed4974f5538b3e574c2ef1865bb92
nixpy version tried: commit 4a0e42d7ef2f2704dd23f75f63ef8c268148ac45

Here is test output:

    ~/repos/nixpy$ python setup.py test
    running test
    running egg_info
    writing nix.egg-info/PKG-INFO
    writing top-level names to nix.egg-info/top_level.txt
    writing dependency_links to nix.egg-info/dependency_links.txt
    reading manifest file 'nix.egg-info/SOURCES.txt'
    writing manifest file 'nix.egg-info/SOURCES.txt'
    running build_ext
    copying build/lib.linux-x86_64-2.7/nix/core.so -> nix
    test_block_data_arrays (nix.test.test_block.TestBlock) ... ok
    test_block_definition (nix.test.test_block.TestBlock) ... ok
    test_block_eq (nix.test.test_block.TestBlock) ... ok
    test_block_find_sources (nix.test.test_block.TestBlock) ... ok
    test_block_id (nix.test.test_block.TestBlock) ... ok
    test_block_multi_tags (nix.test.test_block.TestBlock) ... ok
    test_block_name (nix.test.test_block.TestBlock) ... ok
    test_block_sources (nix.test.test_block.TestBlock) ... ok
    test_block_tags (nix.test.test_block.TestBlock) ... ok
    test_block_timestamps (nix.test.test_block.TestBlock) ... ok
    test_block_type (nix.test.test_block.TestBlock) ... ok
    test_data_array_coefficients (nix.test.test_data_array.TestDataArray) ... ok
    test_data_array_data (nix.test.test_data_array.TestDataArray) ... ok
    test_data_array_definition (nix.test.test_data_array.TestDataArray) ... ok
    test_data_array_dimensions (nix.test.test_data_array.TestDataArray) ... ok
    test_data_array_dtype (nix.test.test_data_array.TestDataArray) ... ok
    test_data_array_eq (nix.test.test_data_array.TestDataArray) ... ok
    test_data_array_exp_origin (nix.test.test_data_array.TestDataArray) ... ok
    test_data_array_id (nix.test.test_data_array.TestDataArray) ... ok
    test_data_array_label (nix.test.test_data_array.TestDataArray) ... ok
    test_data_array_name (nix.test.test_data_array.TestDataArray) ... ok
    test_data_array_sources (nix.test.test_data_array.TestDataArray) ... ok
    test_data_array_timestamps (nix.test.test_data_array.TestDataArray) ... ok
    test_data_array_type (nix.test.test_data_array.TestDataArray) ... ok
    test_data_array_unit (nix.test.test_data_array.TestDataArray) ... ok
    test_range_dimension (nix.test.test_dimensions.TestDimensions) ... FAIL
    test_sample_dimension (nix.test.test_dimensions.TestDimensions) ... ok
    test_set_dimension (nix.test.test_dimensions.TestDimensions) ... ok
    test_feature_data (nix.test.test_feature.TestFeature) ... ok
    test_feature_eq (nix.test.test_feature.TestFeature) ... ok
    test_feature_id (nix.test.test_feature.TestFeature) ... ok
    test_feature_link_type (nix.test.test_feature.TestFeature) ... ok
    test_file_blocks (nix.test.test_file.TestFile) ... ok
    test_file_find_sections (nix.test.test_file.TestFile) ... ok
    test_file_format (nix.test.test_file.TestFile) ... ok
    test_file_sections (nix.test.test_file.TestFile) ... ok
    test_file_timestamps (nix.test.test_file.TestFile) ... ok
    test_multi_tag_definition (nix.test.test_multi_tag.TestMultiTag) ... ok
    test_multi_tag_eq (nix.test.test_multi_tag.TestMultiTag) ... ok
    test_multi_tag_extents (nix.test.test_multi_tag.TestMultiTag) ... ok
    test_multi_tag_feature_data (nix.test.test_multi_tag.TestMultiTag) ... ok
    test_multi_tag_features (nix.test.test_multi_tag.TestMultiTag) ... ok
    test_multi_tag_id (nix.test.test_multi_tag.TestMultiTag) ... ok
    test_multi_tag_name (nix.test.test_multi_tag.TestMultiTag) ... ok
    test_multi_tag_positions (nix.test.test_multi_tag.TestMultiTag) ... ok
    test_multi_tag_references (nix.test.test_multi_tag.TestMultiTag) ... ok
    test_multi_tag_retrieve_data (nix.test.test_multi_tag.TestMultiTag) ... ok
    test_multi_tag_timestamps (nix.test.test_multi_tag.TestMultiTag) ... ok
    test_multi_tag_type (nix.test.test_multi_tag.TestMultiTag) ... ok
    test_multi_tag_units (nix.test.test_multi_tag.TestMultiTag) ... ok
    test_property_definition (nix.test.test_property.TestProperty) ... ok
    test_property_eq (nix.test.test_property.TestProperty) ... ok
    test_property_id (nix.test.test_property.TestProperty) ... ok
    test_property_mapping (nix.test.test_property.TestProperty) ... ok
    test_property_name (nix.test.test_property.TestProperty) ... ok
    test_property_values (nix.test.test_property.TestProperty) ... ok
    test_value_attrs (nix.test.test_property.TestValue) ... ok
    test_value_bool (nix.test.test_property.TestValue) ... ok
    test_value_float (nix.test.test_property.TestValue) ... ok
    test_value_int (nix.test.test_property.TestValue) ... ok
    test_value_str (nix.test.test_property.TestValue) ... ok
    test_proxy_list_contains (nix.test.test_proxy_list.TestProxyList) ... ok
    test_proxy_list_delitem (nix.test.test_proxy_list.TestProxyList) ... ok
    test_proxy_list_getitem (nix.test.test_proxy_list.TestProxyList) ... ok
    test_proxy_list_iterators (nix.test.test_proxy_list.TestProxyList) ... ok
    test_proxy_list_len (nix.test.test_proxy_list.TestProxyList) ... ok
    test_proxy_list_str (nix.test.test_proxy_list.TestProxyList) ... ok
    test_section_definition (nix.test.test_section.TestSection) ... ok
    test_section_eq (nix.test.test_section.TestSection) ... ok
    test_section_find_sections (nix.test.test_section.TestSection) ... ok
    test_section_id (nix.test.test_section.TestSection) ... ok
    test_section_mapping (nix.test.test_section.TestSection) ... ok
    test_section_name (nix.test.test_section.TestSection) ... ok
    test_section_properties (nix.test.test_section.TestSection) ... ok
    test_section_repository (nix.test.test_section.TestSection) ... ok
    test_section_sections (nix.test.test_section.TestSection) ... ok
    test_section_type (nix.test.test_section.TestSection) ... ok
    test_source_definition (nix.test.test_source.TestSource) ... ok
    test_source_eq (nix.test.test_source.TestSource) ... ok
    test_source_find_sources (nix.test.test_source.TestSource) ... ok
    test_source_id (nix.test.test_source.TestSource) ... ok
    test_source_name (nix.test.test_source.TestSource) ... ok
    test_source_sources (nix.test.test_source.TestSource) ... ok
    test_source_timestamps (nix.test.test_source.TestSource) ... ok
    test_source_type (nix.test.test_source.TestSource) ... ok
    test_sources_extend (nix.test.test_source.TestSource) ... ok
    test_tag_definition (nix.test.test_tag.TestTag) ... ok
    test_tag_eq (nix.test.test_tag.TestTag) ... ok
    test_tag_extent (nix.test.test_tag.TestTag) ... ok
    test_tag_features (nix.test.test_tag.TestTag) ... ok
    test_tag_id (nix.test.test_tag.TestTag) ... ok
    test_tag_name (nix.test.test_tag.TestTag) ... ok
    test_tag_position (nix.test.test_tag.TestTag) ... ok
    test_tag_references (nix.test.test_tag.TestTag) ... ok
    test_tag_retrieve_feature_data (nix.test.test_tag.TestTag) ... ok
    test_tag_timestamps (nix.test.test_tag.TestTag) ... ok
    test_tag_type (nix.test.test_tag.TestTag) ... ok
    test_tag_units (nix.test.test_tag.TestTag) ... ok
    test_name_check (nix.test.test_util.TestUtil) ... ok
    test_name_sanitizer (nix.test.test_util.TestUtil) ... ok
    test_unit_is_atomic (nix.test.test_util.TestUtil) ... ok
    test_unit_is_compound (nix.test.test_util.TestUtil) ... ok
    test_unit_is_si (nix.test.test_util.TestUtil) ... ok
    test_unit_sanitizer (nix.test.test_util.TestUtil) ... ok
    test_unit_scalable (nix.test.test_util.TestUtil) ... ok
    test_unit_scaling (nix.test.test_util.TestUtil) ... ok
    test_unit_split (nix.test.test_util.TestUtil) ... ok
    test_unit_split_compound (nix.test.test_util.TestUtil) ... ok
    
    ======================================================================
    FAIL: test_range_dimension (nix.test.test_dimensions.TestDimensions)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/ajay/repos/nixpy/nix/test/test_dimensions.py", line 104, in test_range_dimension
        assert(self.range_dim.index_of(10.) == (round(10./3.14)))
    AssertionError
    
    ----------------------------------------------------------------------
    Ran 108 tests in 1.113s
    
    FAILED (failures=1)

Please have a look

Thanks
Ajay

**Comment by gicmo** [comment]
Just to be sure: @ajayramak did you checkout the current version of NIX? Because we [changed](https://github.com/G-Node/nix/commit/f526c5a21662f7ad22a4300b609a25078b76e556) internals of the range dimension.

**Comment by stoewer** [comment]
Yes, https://github.com/G-Node/nix/commit/7fd231bc753ed4974f5538b3e574c2ef1865bb92 seems to be the latest version.

**Comment by jgrewe** [comment]
well, there is an open pull request ;) (open for 10 days)

**Comment by gicmo** [comment]
DOH! @jgrewe thanks a bunch. merged! Should fix this issue here. :-)

**Comment by jgrewe** [comment]
I keep my fingers crossed :-)
