### ISSUE TITLE
Problem during batch operations

### ISSUE THREAD

**Issue by jgrewe** [G-Node/nixpy#138]
@drumstick12 pointed me to an issue related with batch operations on multiple files.

Consider the following code:

``` python
import nix
import numpy as np
import glob

def create_files(count):
    for i in range(count):
        f = nix.File.open("test_"+str(i)+".h5", nix.FileMode.Overwrite)
        b = f.create_block("test_block_" + str(i), "test")
        da = b.create_data_array("array", "test", data=np.random.rand(1000))
        da.append_sampled_dimension(1.)
        da.unit = "mV"
        da.label = "voltage"
        f.close()
        da = None  # this is essential; code fails, otherwise
        b =  None  # do

def reload_files():
    files = glob.glob('test*.h5')
    for fi in files:
        f = nix.File.open(fi, nix.FileMode.ReadOnly)
        b = f.blocks[0]
        da = b.data_arrays['array']
        data = da[:]
        da = None  # this is essential
        b = None  # do 
        f.close()

if __name__ == "__main__":
    create_files(10)
    reload_files()
```

It creates a few files, stores some data and subsequently re-opens them to read the data. Without setting the variables for the block and the data array explicitly to `None` the code fails with the same H5Lexists: not a location exception.

Setting everything to None, is ok for a few variables, but is really annoying if you open a lot of entities.

**Comment by jgrewe** [comment]
actually we had a similar problem earlier, cf: #78, #88

**Comment by Prabhnith** [comment]
using `import nix` is throwing an error 
![import_nix](https://cloud.githubusercontent.com/assets/11560449/13611661/abac2ab8-e589-11e5-89e5-86c2d453e4a5.png)

but using :
`import nixio as nix` is working fine without giving any errors.
![nixpy_issue](https://cloud.githubusercontent.com/assets/11560449/13611662/abac7b26-e589-11e5-95df-0ff9d2c15db8.png)

**Comment by achilleas-k** [comment]
No longer an issue.
