### ISSUE TITLE
[travis] Test also on OSX 

### ISSUE THREAD

**Issue by gicmo** [G-Node/nixpy#140]
Extend the build matrix to also use OSX. NIX does it already.

**Comment by mpsonntag** [comment]
According to their docs Travis does not support Python under OSX at the moment (https://docs.travis-ci.com/user/languages/python)

**Comment by sudoankit** [comment]
I successfully build NIXPy on OS X.
These are the build instruction I followed.

```
# clone from github
git clone https://github.com/G-Node/nixpy.git

# change directory [ small typo in readme.md of master branch (nix instead of nixpy) ]
cd nixpy 

# build
python setup.py build

# unit tests
python setup.py test

# install 
sudo python setup.py install

```
If there is an error `ld: library not found for -lboost_python`, then install `boost-python` using homebrew,
`brew install boost-python`

Should I pull a request to update README.md, to include a OS X Getting Started Guide?
And, maybe make a pip package `nixpy` on PyPI, for ease of installation?

**Comment by jgrewe** [comment]
@sudoankit a pr about README update would be very welcome. With PyPi we still have to wait because of potential name clashes

**Comment by gicmo** [comment]
@sudoankit adding it to the README would indeed be nice, but this issue is for adding OSX as a build target in the .travis.yml file so that for every pull request we also build nixpy on OSX. ;)

**Comment by sudoankit** [comment]
Yeah. 
I will update travis.yml and the Readme.
This is really interesting and fun. 

Some sources say that Travis  has some problems on OSX's python, so let me try to use homebrew to install NIX, and then build NIXPy using Python on OSX in the build matrix. 
Also, Travis doesn't use the latest  OS X version, so I hope no problems arise due to the new 'rootless' feature in El Capitan. 

I'll keep updating  and reporting if problems arise for guidance.

**Comment by gicmo** [comment]
@sudoankit great! Sounds like a good plan.

**Comment by sudoankit** [comment]
I am pulling a request for to merge the updated README.md.  
Travis integration is on process. (small hiccups led to the delay.)

**Comment by sudoankit** [comment]
For the travis.yml build for OS X, I propose we use `virtualenv`. 
This eliminates the need of `sudo` and it's safer for the OS X build in python.
I too was thinking to create a OS dependency bash script, and then run it in travis.
Waiting for help and suggestions.

**Comment by gicmo** [comment]
@sudoankit actually, I have had some "fun" with travis a few days ago, while converting it to use `trusty`.

Since we use `boost-python` we actually *cannot* use the python 2.7 that is included in the virtual env of Travis, the one in the virtual env is build with different settings then the system one so linking the one in the virtual env against boost-python will get you linker errors. Teh Fun™! So we are actually using the system one. Which is actually not such bad news for OSX support, since we should just switch the container to use the [generic image](https://docs.travis-ci.com/user/trusty-ci-environment#Image-differences-from-Precise) and install python3 also via `apt-get`. Of course we need to create the [build matrix](https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix) manually.
