### ISSUE TITLE
[build] Link error on Arch Linux (libboost_python3)

### ISSUE THREAD

**Issue by achilleas-k** [G-Node/nixpy#145]
On Arch Linux, boost_python libraries use the names `libboost_python` and `libboost_python3` (same convention as OSX it seems).

```
$ locate boost_python
/usr/lib/libboost_python.a
/usr/lib/libboost_python.so
/usr/lib/libboost_python.so.1.60.0
/usr/lib/libboost_python3.a
/usr/lib/libboost_python3.so
/usr/lib/libboost_python3.so.1.60.0
```

The build succeeds if I edit `setup.py` accordingly.

I'm not sure if this is unique to Arch or if there are other distributions that follow this convention.

**Comment by jgrewe** [comment]
on mac, python3 works smoothly with boost 1.6,...

**Comment by achilleas-k** [comment]
This isn't an issue with boost 1.60. It's a problem with the naming convention for the boost_python file names. `setup.py` expects the files to be named `libboost_python-py<majorversion><minorversion>` under Linux, which appears to be true for most common Linux distributions. On Arch, this isn't true. Instead, it uses the convention `libboost_python3` for python3 and simply `libboost_python` for python2.

I mentioned OSX because it happens to use the same naming convention as Arch.

**Comment by gicmo** [comment]
It is probably better to do it the way we do it for the win32 case: just see what is there and have a heuristic to assign the py3/py2 versions.

**Comment by stoewer** [comment]
> It is probably better to do it the way we do it for the win32 case: just see what is there and have a heuristic to assign the py3/py2 versions.

I agree with gicmo. 

A function searching `BOOST_LIBDIR ` for files with names beginning with the following prefixes should actually work on all platforms:

 - `libboost_python-py<major><minor>`
 - `libboost_python-py`
 - `libboost_python<major>`
 - `libboost_python`

**Comment by gicmo** [comment]
I will take care of this.
