### ISSUE TITLE
nixpy build issue

### ISSUE THREAD

**Issue by Prabhnith** [G-Node/nixpy#157]
while executing
`python setup.py build`
error:
`#include <nix.hpp> 
file or directory not found`

**Comment by sudoankit** [comment]
Install `nix` first.
If you use homebrew use `brew install homebrew/science/nixio`.
For details how to install [NIX](https://github.com/G-Node/nix), check out its repository.

**Comment by Prabhnith** [comment]
I installed the nix and other dependencies. Now nixio is installed properly.
Thanks @sudoankit 
Ankit, now nixio is installed, what else I need to do to get started with the project?
