### ISSUE TITLE
TypeError in overview.rst code block

### ISSUE THREAD

**Issue by Prabhnith** [G-Node/nixpy#158]
`# create an empty DataArray to store 2x1000 values
data = block.create_data_array("my data", "nix.sampled", dtype=nix.DataType.Double, shape=(2,1000))
some_numpy_array = np.random.randn(2, 1000)
data[:, :] = some_numpy_array
some_more_data = np.random.randn(2,10)
data.data_extent((2,1010))
data[:, 1000:] = some_more_data`

error in:
`data.data_extend((2,1010))`
`TypeError: 'tuple' object is not callable`

**Comment by jgrewe** [comment]
solved by pr #159
