### ISSUE TITLE
Renaming objects causes error

### ISSUE THREAD

**Issue by achilleas-k** [G-Node/nixpy#164]
Creating a Block in a new NIX file and then attempting to change its name causes an error:

```python
import nixio

nixfile = nixio.File.open("/tmp/foo.hdf5", nixio.FileMode.Overwrite)
block = nixfile.create_block("blockname1", "blocktype")
block.name = "anothername"
```
```
Traceback (most recent call last):
  File "foo.py", line 4, in <module>
    block.name = "anothername"
AttributeError: can't set attribute
```

According to the [API Documentation](https://g-node.github.io/nixpy/api_data.html#block), this should work.

The same occurs with other object types (tested Groups and DataArrays).

**Comment by Prabhnith** [comment]
name and id attributes can't be set. Rest of them we can manipulate and add other attributes too

**Comment by achilleas-k** [comment]
Then I guess the documentation should change?
The "Working with blocks" section shows setting a name on an existing object after it's loaded from a file.
