### ISSUE TITLE
A test fails with v1.1.0

### ISSUE THREAD

**Issue by dEvasEnApati** [G-Node/nixpy#166]
Dear NIX developers

I tried to install nixpy v1.1.0 with NIX v1.1.0. NIX installed and tested fine while nixpy threw the following error when testing:

> ERROR: Failure: ImportError (/home/ajay/repos/nixpy/nixio/core.so: undefined symbol: _ZNK3nix3Tag10getFeatureEy)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/ajay/repos/nixpy/.eggs/nose-1.3.7-py2.7.egg/nose/loader.py", line 418, in loadTestsFromName
>     addr.filename, addr.module)
>   File "/home/ajay/repos/nixpy/.eggs/nose-1.3.7-py2.7.egg/nose/importer.py", line 47, in importFromPath
>     return self.importFromDir(dir_path, fqname)
>   File "/home/ajay/repos/nixpy/.eggs/nose-1.3.7-py2.7.egg/nose/importer.py", line 94, in importFromDir
>     mod = load_module(part_fqname, fh, filename, desc)
>   File "/home/ajay/repos/nixpy/nixio/__init__.py", line 11, in <module>
> ImportError: /home/ajay/repos/nixpy/nixio/core.so: undefined symbol: _ZNK3nix3Tag10getFeatureEy
> .
> .
> .
> FAILED (errors=1)

Please have a look.

Sincerely
Ajay

**Comment by jgrewe** [comment]
Hi Ajay, usually this happens when versions are not in sync. I cannot reproduce the error when installing nix 1.1.0 via homebew. nixpy (version 1.1.0) build and tests run without complaint. 

Can you provide some more info which system you are using, are you building from source or using the packages available via the ppa?

**Comment by dEvasEnApati** [comment]
Hi Jan

I am not able to reproduce this error. I am going to use the packages available on ppa. 

Thanks

Sincerely
Ajay
