### ISSUE TITLE
[pycore] Group container methods should use parent Block and link logic

### ISSUE THREAD

**Issue by achilleas-k** [G-Node/nixpy#180]
**Adders** (e.g., `Group._add_data_array_by_id`) should check if the item is a child of the parent Block.

**Getters** (e.g., `Group._get_data_array_by_id`) do not take into account that the items are linked by ID.

Similar issues exist for **deleters** and **contains checkers**.

**Comment by stoewer** [comment]
Supposed to be closed by #181
