### ISSUE TITLE
some problem with Boost.Python and string types

### ISSUE THREAD

**Issue by maksutovaynur** [G-Node/nixpy#183]
When I try to create property for section:
Traceback (most recent call last):
    sec.create_property(str('A1'), str('mV'), [params[0]])
Boost.Python.ArgumentError: Python argument types in
    Section.create_property(Section, str, str, list)
did not match C++ signature:
    create_property(nix::Section {lvalue}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, _object*)

When I call create_block or create_section methods, it throws exception like above, but I solved it converting string objects by str function. With create_property this doesn't work.

**Comment by stoewer** [comment]
The method `create_property` takes only two parameters: the first parameter is the property name (a string) and the second one is a list of of value objects. Please take a look at the [documentation](https://g-node.github.io/nixpy/api_metadata.html#add-and-remove-properties).

**Comment by jgrewe** [comment]
Maybe as a little helper: 

You can create properties in two ways:

````
import nixio as nix
f = nix.File.open("test.nix")
s = f.create_section("Foo", "foo")
# 1st with a list of values
s.create_property("bar", [nix.Value("a string property")])
# 2nd shortcut for simple props
s["baz"] = "another string property"
````

**Comment by maksutovaynur** [comment]
Thank you! And excuse me for my mistake. Now it works properly.
>Вторник, 19 июля 2016, 13:42 +02:00 от Jan Grewe <notifications@github.com>:
>
>Maybe as a little helper: 
>You can create properties in two ways:
>import nixio as nix
f = nix.File.open("test.nix")
s = f.create_section("Foo", "foo")
# 1st with a list of values
s.create_property("bar", [nix.Value("a string property")])
# 2nd shortcut for simple props
s["baz"] = "another string property"
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Aynur Maksutov
