### ISSUE TITLE
[build] build broken because of deleteDimensions

### ISSUE THREAD

**Issue by gicmo** [G-Node/nixpy#197]
Build is broken do to issue #190. Fixed in the `pycore` branch but not on master. I looked but sadly the changes in PR #192 are not separate into `pycore` and `libnix` therefore a back port is not easily possible. We either merge the `pycore` branch fast, of fix it also on master.

**Comment by achilleas-k** [comment]
At the risk of delaying the merge of pycore into master, I'm preparing a separate PR for master to make it compatible with the API change.

**Comment by achilleas-k** [comment]
PyCore merged.
