### ISSUE TITLE
import error nixio.pycore.file 

### ISSUE THREAD

**Issue by dEvasEnApati** [G-Node/nixpy#205]
Hi guys

I tried to build and install latest nixpy with latest nix. Running 'python setup.py test' gave no error.
However, when I try "python -c 'import nixio'", I get an error:
File "<string>", line 1, in <module>
  File "/home/maksutov/.local/lib/python2.7/site-packages/nixio-1.1.0-py2.7-linux-x86_64.egg/nixio/__init__.py", line 11, in <module>
    from nixio.pycore.file import File, FileMode
ImportError: No module named pycore.file

Could you take a look?

Sincerely
AJ

**Comment by achilleas-k** [comment]
Fixed. Was most likely leftover pyc files.
Cleaned with `find -iname "*pyc" -exec rm {} \;`.

**Comment by achilleas-k** [comment]
Reopening.
The issue wasn't pyc files but the setup script.

I need to include every (sub)package in the `packages` list.
