### ISSUE TITLE
Single value indexing of DataArray returns 0d array

### ISSUE THREAD

**Issue by achilleas-k** [G-Node/nixpy#275]
When you access a single element from a DataArray, you get a 0d array. These are generally hard to work with since they don't behave like normal arrays or scalars.

In addition, this breaks the current implementation of `apply_polynomial` in pycore since `np.polyval` relies on iteration over the supplied array.

OBSERVE:
```python
import nixio as nix


nixfile = nix.File.open("nixfile.nix", mode=nix.FileMode.Overwrite,
                        backend="h5py")
blk = nixfile.create_block("blk", "blk")
dataarray = blk.create_data_array("da", "da", data=[1.1, 2.5, 3.42])

# accessing single value returns 0d array
print("Shape {}".format(dataarray[1].shape))
print("Ndim  {}".format(dataarray[1].ndim))

for v in dataarray:
    print("Shape {}".format(v.shape))
    print("Ndim  {}".format(v.ndim))

# these can be hard to work with if you're writing code that generally works
# with arrays
val = dataarray[2]
try:
    val[:]
except IndexError as exc:
    print("IndexError caught: {}".format(exc))

try:
    for v in val:
        print(v)
except TypeError as exc:
    print("TypeError caught: {}".format(exc))

# currently, it also breaks polynomial coeffients
dataarray.polynom_coefficients = (0, 1.0)

print(dataarray[0])
```

Three options:
1. Keep the return value as is and fix `apply_polynomial`.
2. Return a normal numpy array with shape `(1,)`.
3. Return a numpy scalar or python value.

1 & 3 don't solve the issue of iterating over the value returned by indexing an array, but that might be OK. 3 in particular is probably the most pythonic since it mimics indexing lists or any other iterable. 2 is probably a _general_ solution, but it's not nice since it doesn't behave the way iterables tend to work (not even numpy arrays).

I'd love to hear thoughts.

**Comment by jgrewe** [comment]
I would prefer solution 2 for the following because it seems, as you said, the more general solution. From the user's pow you have to handle things always in the same way. Changing this might also affect the other functions to get data like retrieve data etc.?
