### ISSUE TITLE
strange error during retrieve data

### ISSUE THREAD

**Issue by jgrewe** [G-Node/nixpy#288]
Consider the following situation: I have a multiTag with a bunch of positions and extents. It references a DataArray named "Spikes-1" which, obviously, contains spike times.
Now I want to get the spike times related to each run of position, extent pair. 
I am using nixio 1.4.3 using the h5py backend.

```
>> indices = np.where(mtag.positions[:] >= start_time & mtag.positions[:]  < end_time)
>> print(type(inidices[0]))
<class 'numpy.int64'>
for i in indices:
   spikes = mtag.retrieve_data(i, "Spikes-1")

/usr/lib/python3.6/site-packages/nixio/data_array.py in __complete_slices(shape, index)
    294             index = slice(0, shape)
    295         else:
--> 296             raise IndexError('Invalid index')
    297         return index
    298 
```

The following works:
```
for i in indices:
   spikes = mtag.retrieve_data(int(i), "Spikes-1")
```

**Comment by achilleas-k** [comment]
https://github.com/G-Node/nixpy/blob/d88853c568815148a19494ab8a01d14f661f94e9/nixio/data_array.py#L272
Looks like the data array slicing methods for DataArray do type checking using `type(index) is <type>`, which is discouraged for this exact reason (`numpy.int64 is not int`). We should use `isinstance()` and abstract base classes ([numbers.Number](https://docs.python.org/2/library/numbers.html)).

**Comment by achilleas-k** [comment]
This doesn't work with the NIX backend, does it? I think the numpy index fails to go through (`No registered converter ...`)

**Comment by jgrewe** [comment]
actually, I do not know. hdf5 backend, not available, sorry
