### ISSUE TITLE
Restrictions for type of uncertainty in nix and odML

### ISSUE THREAD

**Issue by JuliaSprenger** [G-Node/nixpy#319]
Currently the only types accepted for uncertainties are integer and float in Nix. In odML however, there is no restriction when generating an odML document, but for documents loaded from disc all uncertainties have the type string.
I am not sure if it makes sense to also allow string uncertainties in Nix or if odML uncertainties should also be restricted to integer and float. One example for needing a string as uncertainty would be to store something like '2 standard deviations' but I am not sure if this is a real use case.
Any opinions on that?

**Comment by achilleas-k** [comment]
Well I suppose you just answered the question I asked a minute ago in the corresponding [issue in odML](G-Node/python-odml#294).

I don't know how I feel about that. Perhaps if one wants to be descriptive in that way the solution would be to store a secondary property for the uncertainty, though that defeats the purpose of having uncertainties... I guess?

I'm generally leaning towards restricting uncertainties to floats everywhere, unless I hear a compelling reason not to.

**Comment by JuliaSprenger** [comment]
How about using the nix/odml dtype also for the corresponding uncertainties?

**Comment by achilleas-k** [comment]
That does sound like it would make sense. Int uncertainty for int values, float for floats...

**Comment by jgrewe** [comment]
Imho, they should only be numeric. I do not remember why they would allow string in odml...

**Comment by achilleas-k** [comment]
## It has been decided that uncertainty will be limited to `float`
