### ISSUE TITLE
[DataFrame] Export to CSV

### ISSUE THREAD

**Issue by hkchekc** [G-Node/nixpy#345]
for the no-bindings-dev branch DataFrame object, adding a function for exporting the dataframe to a csv format file will be nice

**Comment by jgrewe** [comment]
exporting it to pandas, if available, would also be nice

**Comment by hkchekc** [comment]
> exporting it to pandas, if available, would also be nice

have written a simple function for this, will make a pull request after the core part of DataFrame is merged
