### ISSUE TITLE
DataFrame creation

### ISSUE THREAD

**Issue by achilleas-k** [G-Node/nixpy#353]
The DataFrame creation function is a bit complicated and I think it requires too much work from the user.
Currently, in the tests in PR #352 create DataFrames in the following manner

```python
di = {'name': int, 'id': str, 'time': float, 'sig1': np.float64, 'sig2': np.int32}
arr = np.arange(1500).reshape((300, 5))
self.block.create_data_frame("test df", "signal1", data=arr, col_dict=di)
```

Let me simplify the example a bit by assuming the following case (same form as above):
```python
data = np.array([[0, 1, 2], [10, 20, 30]])
col_dict = {"Name": str, "Age": int, "Success": bool}
blk.create_data_frame("dfa", "DF", data=data, col_dict=col_dict)
```

There's a few issues here. I'm going to list some creation methods and discuss how I think they should work.

### Method A
The data in `arr` are all of the same type, since it's a numpy array. If a list is provided instead, to add data of mixed types:
```python
data = [["Bob", 10, False], ["Jane", 9, True]]
col_dict = {"Name": str, "Age": int, "Success": bool}
blk.create_data_frame("dfa", "DF", data=data, col_dict=col_dict)
```
We get an error where the creation method tries to get the shape of the data:
https://github.com/G-Node/nixpy/blob/c5b02465ffefa07acaf78d6183ab746ecbd8ac12/nixio/block.py#L200

So the method expects a numpy array or at least something that has an obj.shape property.

### Method B
If we create a numpy array with a compound (struct) data type:
```python
dt = [("Name", nix.util.vlen_str_dtype), ("Age", nix.DataType.Int32), ("Tested", nix.DataType.Bool)]
data = np.array([("Bob", 10, False), ("Jane", 9, True)], dtype=dt)
col_dict = {"Name": str, "Age": int, "Success": bool}
blk.create_data_frame("dfb", "DF", data=data, col_dict=col_dict)
```
We get an error at the point where the library attempts to unpack `shape` into two values:
https://github.com/G-Node/nixpy/blob/c5b02465ffefa07acaf78d6183ab746ecbd8ac12/nixio/data_frame.py#L28

The issue is that our data is actually one-dimensional, so `shape == (2,)`

Another subtler issue here is that it requires specifying the column types in two locations. The numpy array `dtype` requires a list of tuples `(name, type)` and the `col_dict` requires a dictionary `{name: type}`. Of course, this duplicate effort can probably be mitigated by the user if they create a list of column names and a list of column types, but our library should be doing this work for the user instead. More on this later.

### Method C
Using `col_names` and `col_dtypes` instead of the dictionary has the same issue:
```python
colnames = ["Name", "Age", "Success"]
coltypes = [str, int, bool]
dt = list(zip(colnames, coltypes))
data = np.array([("Bob", 10, False), ("Jane", 9, True)], dtype=dt)
blk.create_data_frame("dfb", "DF", data=data, col_names=colnames, col_dtypes=coltypes)
```
The only difference here is that the dictionary is created by the `create_data_frame` method internally.

### Method D
It should be possible to create a DataFrame without any data. This is possible for DataArrays.

```python
col_dict = {"Name": str, "Age": int, "Success": bool}
df = blk.create_data_frame("dfd", "DF", col_dict=col_dict)
df.append_rows([("Bob", 10, False), ("Jane", 9, True)])
```

In the case of the DataArray, if data are not supplied, the shape is required. This isn't binding, since axes can be resized, but the number of dimensions can't change, so the shape argument defines the dimensionality. We use the shape argument instead of simply an `ndim` argument however because if the user does know the shape of their data, it's more efficient to create the dataset with the given size and fill the preallocated space than it is to resize one or more times.

In the case of the DataFrame, we don't even need the shape information, since internally, DataFrames are one-dimensional. Each element of the internal dataset represents a DataFrame row and the columns are represented by the components of the struct (compound datatype). Initialising the internal HDF5 dataset with `shape=(0,)` is perfectly fine, since the single dimension can be extended when data are provided for writing. We could of course keep the shape argument (or perhaps call it `length` or `nrows`) for the same reason we have it in DataArray.

The `append_rows()` method above should also work with a structured numpy array (compound datatype), like the one created in Method B.

### Method E
I think it should also be possible to just create a DataFrame with a preexisting structured numpy array, since all the information we need is there.

```python
dt = [("Name", nix.util.vlen_str_dtype), ("Age", nix.DataType.Int32), ("Tested", nix.DataType.Bool)]
data = np.array([("Bob", 10, False), ("Jane", 9, True)], dtype=dt)
blk.create_data_frame("dfe", "DF", data=data)
```

Data is provided on creation and the column names and dtypes are available through the data's dtype.

### Method F
Even further, I'd say we should even be doing type inference the same way DataArray creation does, by allowing a DataFrame to be created from a list of tuples.

```python
def cf(blk):
    data = [("Bob", 10, False), ("Jane", 9, True)]
    blk.create_data_frame("dfe", "DF", data=data, col_names="Name", "Age", "Tested")
```

In this case, we could require column names or even have placeholder names that we can change later (column renaming should be supported).

-------

I think if all methods above end up working as expected, we cover all (or most) use cases.
- Creating a structured array in numpy (Methods B, C, E) provides the most fine-grained control for the user, but it is a bit of a hassle when one needs to create a quick "table" on the fly.
- Quick creation is supported by inferring types (Method F).
- Empty DataFrame creation is supported. This is useful for cases where one wants to create objects as placeholders to be filled later, for instance for streaming data into the file row by row (Method D).
- The column dictionary can be supplied directly for full control but in a more structured way (Method A).

Notes:
- If all these methods are supported, more forms would also be possible. For instance, if we can create empty DataFrames, then the columns can be defined either using names and types separately or as a dictionary.
- If either a dictionary is provided or types, the data should be converted to fit into those types.
- If types and names are provided both through a dictionary and the `col_names` and `col_types` arguments, an error should be thrown.

**Comment by hkchekc** [comment]
Don't think there is anything left. Close it?
