### ISSUE TITLE
Inconsistencies between NIX and NIXPy validators

### ISSUE THREAD

**Issue by achilleas-k** [G-Node/nixpy#369]
It seems the validator in NIXPy regards dimensionality in the opposite way of NIX.

Example:
- A `DataArray` with shape `(100, 2)` with dimensions:
    - `SampledDimension`.
    - `SetDimension` with two labels.

This is valid according to NIX but invalid according to NIXPy.

Other combinations (reversing shape and/or dimension) have consistent results. I need to investigate more.

**Comment by hkchekc** [comment]
I am just wondering should the numbers of label equals to the size of dataarray, the dimensionality of the dataarray or what?

I think I understood the requirement for the length of label as len(dim.labels)  == len(da) at that time

**Comment by achilleas-k** [comment]
There's two things:
- The number of dimensions should equal the rank (number of dimension) of the DataArray.
- Each dimension length should be equal to the length of the corresponding dimension of the data array. What we regard as the length of the dimension depends on its type:
    - For SampledDimension, it doesn't matter, since it only holds the sampling interval.
    - For RangeDimension, the number of ticks should equal the length of the corresponding DataArray dimension.
    - For SetDimension, the length of the labels should equal the length of the corresponding DataArray dimension.

It looks like the issue is concentrated here:
https://github.com/G-Node/nixpy/blob/98151edecc92e25c487ebb4935dfaa8f40a0c977/nixio/validate.py#L111-L123

All the dimensions are compared against `len(da)`, but `len(da)` only gives you the length of the first dimension. For a DataArray with shape `(a, b, c)`, the first Dimension object should be compared against `a, the second Dimension should be compared against `b`, and the third against `c`.

**Comment by achilleas-k** [comment]
Closed via #370
