### ISSUE TITLE
Fix references to _offset and _count in DataView

### ISSUE THREAD

**Issue by achilleas-k** [G-Node/nixpy#405]
DataView contains leftover references to `_offset` and `_count` in its `write_data` function (see linked line).

https://github.com/G-Node/nixpy/blob/422e5c29720b42bb12bff3a2cdb580753e199272/nixio/data_view.py#L84

The DataView class no longer holds these two properties, but instead keeps a `slice`, which holds the equivalent to offset as `slice.start` and the equivalent to count as `slice.stop - slice.start` (normally this would require dividing by step, but in our case step is always 1).

We never test writing through a DataView so this wasn't caught in the rewrite for 1.5 when the bindings were removed.  We should add some tests.

**Comment by hkchekc** [comment]
Same for https://github.com/G-Node/nixpy/blob/bb99824917d7d0bbeac9454516907097f9a773d5/nixio/multi_tag.py#L112
