### ISSUE TITLE
Enforce unique column names for DataFrame (?)

### ISSUE THREAD

**Issue by achilleas-k** [G-Node/nixpy#433]
We don't enforce unique column names for DataFrame objects but we do have methods for getting columns by name.

EDIT: Since we use a compound data type to represent DFs and the column names become the name of the member, non-unique members will cause an error at the HDF5 level.  We should catch this early.

**Comment by hkchekc** [comment]
I am wondering which is the correct exception that should be raised. ValueError?

**Comment by achilleas-k** [comment]
For objects we have a DuplicateName custom exception.
https://github.com/G-Node/nixpy/blob/bbbb4d9ace230dfaf9c82f5837ffa194899005a0/nixio/exceptions/exceptions.py#L11

We can't use that here since the message isn't appropriate.  Let's create a new type of custom Exception for this as well `DuplicateColumnName`.  The message should be something like:
"Column names for a DataFrame have to be unique."
