### ISSUE TITLE
Formatting of library version string

### ISSUE THREAD

**Issue by JuliaSprenger** [G-Node/nixpy#456]
For development versions of the library currently a '0.0.dev' format is used. This leads to errors when comparing versions with other release versions strings formatted in a '0.0.0'.

This is currently an issue in the context of the Neo-NixIO:

```python
import neo
neo.NixIO('test.nix','ow')
```
yields for pip installed versions of `neo==0.8.0` and  `nixio==0.9.dev` (i.e. the current master)

```
  File "~/anaconda3/envs/test/lib/python3.8/distutils/version.py", line 337, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'str' and 'int'
```

My suggestion would be to use also for development versions a format that is compatible with common version comparison mechanisms, like '0.0.0.dev'.

**Comment by JuliaSprenger** [comment]
Note: The issue persists also when nixio is installed via pip, which extends the version string from `1.5.dev` to `1.5.dev0`.

**Comment by achilleas-k** [comment]
Thanks Julia.  This is indeed much better.
