### ISSUE TITLE
DataView: return scaled values if polynom_coefficients

### ISSUE THREAD

**Issue by DanBenHa** [G-Node/nixpy#482]
A `DataView` returned by `MultiTag.tagged_data` should return the scaled values if the referenced `DataArray` has `polynom_coefficients`.

**Comment by achilleas-k** [comment]
That's a good point.  The root of the issue (implementation wise) is that polynomial coefficients (and the expansion origin) are attached to DataArrays, whereas Tags retrieve data through the DataSet base class, which has no knowledge of DataArray features.

@jgrewe Do you agree that the DataView should respect coefficients?  How would we handle this?

**Comment by jgrewe** [comment]
Oh wow, I almost forgot about that feature... I think the dataView should return the scaled values... 
How to solve it, tricky question, need to have a look on the Cpp side as well

**Comment by achilleas-k** [comment]
Checked NIX and this is definitely a NIXPy bug, because NIX does this properly and I neglected to do it in NIXPy.

In NIX, the DataView keeps a reference to the DataArray and calls its `read` function which applies the coefficients.
