### ISSUE TITLE
AliasRangeDimension documentation and simplification

### ISSUE THREAD

**Issue by DanBenHa** [G-Node/nixpy#500]
Storage of spike times is suggested to be implemented via AliasRangeDimension: https://nixio.readthedocs.io/en/latest/storing_data.html#aliasrangedimension
Makes sense, sounds simple.

Unfortunately, the documentation seems to be out-of-date on this, even though it appears to be automatically generated: `DataArray` is still said to have the method `append_alias_range_dimension`.
There's also a compatibility test that uses the method and apparently doesn't fail in the automatic testing: https://github.com/G-Node/nixpy/blob/fa561104305c73b233d9903d601440c390e2c042/nixio/test/test_nix_compatibility.py#L297

So, since `append_alias_range_dimension` is gone from `DataArray`, I would intuitively think that passing no arguments to the method `append_range_dimension` would just do what the removed method did. But it doesn't. Sifting through the tests I found the new way of creating an alias range dim is to manually link it... https://github.com/G-Node/nixpy/blob/fa561104305c73b233d9903d601440c390e2c042/nixio/test/test_dimensions.py#L380
This works and I can use `MultiTag` to retrieve data from a `DataArray` with an alias range dimension. But again, documentation, here in the docstring of `DataArray`, would've been nice. Storing spike times is such a core function.

Is it necessary to have the possibility of an unlinked `RangeDimension`? If no, I'd suggest just linking against the calling `DataArray` if no ticks are passed in `append_range_dimension`.

**Comment by jgrewe** [comment]
You are right that the documentation lacks behind. We were kind of hard-pressed to release the 1.5 even without the documentaion updates. We could actually need help with this. 
Indeed the AliasRangeDimension has been replaced by a RangeDimension linking to the parent DataArray itself. 
I intend to indeed make change the ```append_range_dimension``` to do exactly what you suggest. When called without ticks, or a link, it refers to the calling DataArray.

Further I thought about re-introducing some functions to easy the transition: ```RangeDimension.is_alias``` and maybe also ```DataArray.append_range_dimension``` that would be deprecated.

**Comment by jgrewe** [comment]
@DanBenHa I am closing this issue. If you feel like it please check out the [docs](readthedocs.org/projects/nixpy) if you find the information appropriate or would like to have more (in particular the the Change in 1.5 page) .
Thanks!
