### ISSUE TITLE
Clarification: Bindings for C++ NIX

### ISSUE THREAD

**Issue by schmitts** [G-Node/nixpy#515]
Hi!

The README says: "The setup script will automatically build the bindings for NIX if it is detected on the system, otherwise only the pure Python version will be installed." - is this still true? I don't see any generated bindings in 1.5.0.

Thanks,

Sebastian

**Comment by jgrewe** [comment]
dear @schmitts you are right, this should indeed no longer be stated in the README. We dropped the c++ bindings in favor of the python native implementation which makes a lot of things easier... 
The respective lines will be removed, thanks for bringing it up!

**Comment by jgrewe** [comment]
the section has been removed from the README, closing this
