### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by jgrewe** [G-Node/nixpy#81]

**Comment by stoewer** [comment]
Does someone know what this issue was about?

**Comment by jgrewe** [comment]
the only thing that I can imagine are the installation instructions in the documentation. But honestly, I have no clue

**Comment by jgrewe** [comment]
Actually, I am by now pretty sure, it was related to the documentation because it was opened the same day, the tutorial issue was created.

**Comment by stoewer** [comment]
> Actually, I am by now pretty sure, it was related to the documentation because it was opened the same day, the tutorial issue was created.

OK, this makes sense. Thanks.

**Comment by jgrewe** [comment]
solved with pr #135
