### ISSUE TITLE
has_property_by_name takes longer when invoked via block.metadata

### ISSUE THREAD

**Issue by cgars** [G-Node/nixpy#85]
The fellowing code:

``` python
nix_file = nix.File.open('/home/garbers/foo.h5', nix.FileMode.ReadOnly)

profile.run('nix_file.blocks[0].metadata.has_property_by_name(\'Genotype\')')
profile.run('nix_file.sections[0].has_property_by_name(\'Genotype\')')
print nix_file.blocks[0].metadata == nix_file.sections[0]

nix_file.close()
```

leads to this output:

15 function calls in 0.120 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        4    0.000    0.000    0.000    0.000 :0(getattr)
        1    0.000    0.000    0.000    0.000 :0(hasattr)
        2    0.000    0.000    0.000    0.000 :0(isinstance)
        1    0.000    0.000    0.000    0.000 :0(setattr)
        1    0.000    0.000    0.000    0.000 :0(setprofile)
        1    0.120    0.120    0.120    0.120 <string>:1(<module>)
        1    0.000    0.000    0.000    0.000 file.py:20(**init**)
        1    0.000    0.000    0.000    0.000 file.py:37(blocks)
        1    0.000    0.000    0.120    0.120 profile:0(nix_file.blocks[0].metadata.has_property_by_name('Genotype'))
        0    0.000             0.000          profile:0(profiler)
        1    0.000    0.000    0.000    0.000 proxy_list.py:18(**init**)
        1    0.000    0.000    0.000    0.000 proxy_list.py:27(**getitem**)

15 function calls in 0.000 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        4    0.000    0.000    0.000    0.000 :0(getattr)
        1    0.000    0.000    0.000    0.000 :0(hasattr)
        2    0.000    0.000    0.000    0.000 :0(isinstance)
        1    0.000    0.000    0.000    0.000 :0(setattr)
        1    0.000    0.000    0.000    0.000 :0(setprofile)
        1    0.000    0.000    0.000    0.000 <string>:1(<module>)
        1    0.000    0.000    0.000    0.000 file.py:27(**init**)
        1    0.000    0.000    0.000    0.000 file.py:71(sections)
        1    0.000    0.000    0.000    0.000 profile:0(nix_file.sections[0].has_property_by_name('Genotype'))
        0    0.000             0.000          profile:0(profiler)
        1    0.000    0.000    0.000    0.000 proxy_list.py:18(**init**)
        1    0.000    0.000    0.000    0.000 proxy_list.py:27(**getitem**)
True

For some reason the call to "has_property_by_name" seems to take (way) longer when invoked through the Blocks metadata compared to being invoked on the same section directly. This issue seems to be dependent on the amount of sections present in the file as it those only "apear" for files with quite a lot of sections (therefore i do not link to foo.h5 here as it is ~150mb; you can find it on gate.g-node under /groups/wachtler/share)

**Comment by achilleas-k** [comment]
Internals have been heavily rewritten since this was opened and are much more efficient now.  Closing.
